services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/home/vscode/cryptography
        working_dir: /home/vscode/cryptography
        stdin_open: true
        tty: true
        stop_grace_period: 0s
